### ISSUE TITLE
Try NFS mounting instead of shared folder to increase file system performance

### ISSUE THREAD

**Issue by onnimonni** [Seravo/wp-vagrant#10]
Wordpress seems a bit sluggish

**Comment by ottok** [comment]
Make sure to use 'if virtualbox' etc so that people running Vagrant in Linux containers are not negatively affected.

**Comment by ottok** [comment]
Please comment why the issue was closed for future reference.

**Comment by onnimonni** [comment]
NFS mounting was way more slower in our test cases than just basic mounting.

This was tested under OS X yosemite.
