### ISSUE TITLE
Add `vagrant push` to push your project to WP-palvelu.fi

### ISSUE THREAD

**Issue by anttiviljami** [Seravo/wp-vagrant#11]

**Comment by onnimonni** [comment]
I think the `git push production` would be better? And to run appropriate hooks simultaneously

**Comment by anttiviljami** [comment]
`git push production` indicates that we want to push to a remote called _production_, that's fine if the remote is defined. 

I think `vagrant push` is standard for pushing a vagrant repo to a defined staging repo. We wouldn't want to push straight to production anyways.

**Comment by ottok** [comment]
We already had it, and then removed it in https://github.com/Seravo/wp-palvelu-vagrant/commit/792d6741bb734cea6fa739c7808f59eed05e991a

**Comment by anttiviljami** [comment]
that's different. we had push production db and push production uploads, but nothing for git push
