### ISSUE TITLE
Upgrade PHPUnit?

### ISSUE THREAD

**Issue by 0is1** [Seravo/wp-vagrant#22]
Current box have:

```

phpunit --version
PHPUnit 3.7.28 by Sebastian Bergmann.
```

But for example wp-cli [plugin unit test](http://wp-cli.org/docs/plugin-unit-tests/) require 4.8.x

Any plans to upgrade PHPUnit?

**Comment by anttiviljami** [comment]
We use the phpunit available from the standard ubuntu apt-repo. Is there a preferred install source, a ppa perhaps?

Meanwhile, I suggest you run phpunit on the host machine. Can't use wp-cli with it though. :/

**Comment by 0is1** [comment]
Ok.

And actually wp-cli plugin unit test seems to be working with current version of PHPUnit too (at least my small test worked), so it looks like there's no need to do anything at the moment :)
