### ISSUE TITLE
Implement wp-xdebug-on and wp-xdebug-off commands

### ISSUE THREAD

**Issue by ottok** [Seravo/wp-vagrant#39]
Xdebug make PHP run much slower. We might want to disable it by default, but first we need to introduce the commands mentioned in the title to allow easy enabling of Xdebug.

Follow the examples at https://github.com/Varying-Vagrant-Vagrants/VVV/wiki/Code-Debugging#cachegrind and https://github.com/Varying-Vagrant-Vagrants/VVV/tree/develop/config/homebin but remember to keep our `wp-` naming scheme for our custom commands.

**Comment by ottok** [comment]
We need the same for Browsersync too. Most devs don't use it and having it enabled by default just pollutes the Nginx error logs with port 1337 errors..

**Comment by ottok** [comment]
Implementing this could would solve #16 if we then make Xdebug off by default.

**Comment by ottok** [comment]
Currently the manual steps to disable Xdebug is something like: 
```
apt remove php-xdebug
wp-restart-php5-fpm
wp-restart-php7-fpm
```

..and the reverse do enable it.

**Comment by l3ku** [comment]
Development currently in process at [feature-wp-xdebug-commands](https://github.com/Seravo/wp-palvelu-vagrant/tree/feature-wp-xdebug-commands).

**Comment by ottok** [comment]
@l3ku If you have something half-done in the branch linked above, and you want to finish it, then finish it. If you don't intend to finish it, then deassign this issue from yourself and leave a final comment about what you did so somebody else can pick off and continue.

**Comment by l3ku** [comment]
The branch has above has now been deleted, as the development of this feature has been moved to the relevant repository.

**Comment by l3ku** [comment]
The commands were implemented in 7bc970.
