### ISSUE TITLE
Asset proxy failing to load static files from production

### ISSUE THREAD

**Issue by l3ku** [Seravo/wp-vagrant#47]
The asset proxy fails to get static files from the production instance even with proper config.yml configuration, resulting as 404 errors when accessing the local site. Steps to reproduce:

1.  Clone Seravocom (private) repo and switch to legacy branch
2. Run `vagrant up` in repo and don't pull production db (yet)
3. Run `vagrant ssh` and run `wp-pull-production-db` in the virtual machine, check that all presented site urls are valid
4. Check local site in browser, static files give 404 error codes
5. Attempt to run `wp-use-asset-proxy` in vagrant, does not fix the issue

There has also been at least one customer report on this issue. This could originate from some overlapping Nginx configurations, but we should look more thoroughly into this.

**Comment by ottok** [comment]
The problem was caused due to /wordpress/wp-content/ not being a symlink to /wp-content/.
Fixed it now for wp-palvelu.fi.
