### ISSUE TITLE
Vagrant box website fails to load out-of-the-box, home url wrongly https://seravo-wordpress.local'

### ISSUE THREAD

**Issue by ottok** [Seravo/wp-vagrant#59]
For some Vagrant box build/start related issue the home url is occasionally `https://seravo-wordpress.local'` after boot.

```
vagrant@development:~$ env | grep DEFAULT_DOMAIN
DEFAULT_DOMAIN=seravo-wordpress.local
```

Quick workaround to continue broken box is to issue:
```
vagrant@development:~$ wp search-replace https://seravo-wordpress.local https://wordpress.local --all-tables
```

**Comment by ottok** [comment]
I believe this was fixed via 9dd32bcaaa1bc4493bc1ddaccfcc2c6bc85f5bc5

Maybe @nellileinonen could test the latest seravo/wordpress-beta version 20200610.0.0 and tell me if you are able to reproduce this issue anymore?

**Comment by nellileinonen** [comment]
No, I couldn't reproduce this issue anymore with seravo/wordpress-beta version 20200610.0.0. Everything worked ok

**Comment by ottok** [comment]
I have not been able to reproduce this either, so indeed 9dd32bc fixed it. Closing issue.
