### ISSUE TITLE
Benchmark base boxes

### ISSUE THREAD

**Issue by elguitar** [Seravo/wp-vagrant#69]
There are serious performance issues with the IO on the current Seravo Vagrant box.

We should check whether the issues exist in the plain base box too.

We should also benchmark whether other base boxes work better, if the current base box is to blame.

**Comment by elguitar** [comment]
Also, if we track the performance problem down to Virtualbox, we should probably switch providers all together. This would need a base box switch too.

**Comment by elguitar** [comment]
We should really do this benchmark, but we should first make other strategic decisions about our Vagrant box.

**Comment by JoosuaKoskinen** [comment]
Researched this a while back and found some Ubuntu box benchmarks results. There were slight differences but nothing major if I recall correctly.

We should do some benchmarking on our box but we don't use a base box anymore so will close this for now.
