### ISSUE TITLE
Add readme page which has links into installed apps and into wp-palvelu readme

### ISSUE THREAD

**Issue by onnimonni** [Seravo/wp-vagrant#9]
Make an php file which reads links from config.yml and shows the features of this vagrant box.
These are:
- webgrind
- mailcatcher
- terminal
- adminer
- wordpress

**Comment by onnimonni** [comment]
@anttiviljami do you have visual idea for this?

**Comment by anttiviljami** [comment]
```
<h1>Features</h1>
<ul>
<li><a href="#">wordpress</a></li>
<li><a href="#">webgrind</a></li>
<li><a href="#">mailcatcher</a></li>
<li><a href="#">terminal</a></li>
<li><a href="#">adminer</a></li>
</ul>
```

This good enough?

**Comment by ottok** [comment]
Currently a subdomain *info* is added in line https://github.com/Seravo/wordpress/blob/master/Vagrantfile#L279 but no such virtualhost is defined in Nginx, and there is no location where to put the index file discussed in this issue.

**Comment by ottok** [comment]
Info subdomain also referenced in wp-vagrant-activation: https://github.com/Seravo/wp-palvelu-vagrant/blob/master/roles/scripts/files/wp-vagrant-activation

Loose ends like that should either be implemented correctly or cleaned away.

**Comment by ottok** [comment]
Cleaned away in 4429aaf8d708d573f4dd703762a5877b23c444ab
